### ISSUE TITLE
frontend/dist/template/page: no such file or directory

### ISSUE THREAD

**Issue by Yosutta** [i-love-flamingo/commerce-demo-carotene#10]
Hi i'm new to the concept of working with framework such as flamingo. I have a problem that i have been trying to solve for a while now but it doesn't seems like there is anything i can do about it.

After i installing commerce-demo-carotene with the "Run local from source code" method:
I open localhost:3210 on a browser, it show this single line 
"open frontend/dist/template/page: no such file or directory"

I check the folders and there in the frontend folder, there are only these available :

<img src="https://user-images.githubusercontent.com/66834349/97948601-a6d90200-1dc3-11eb-9567-037a92658d75.png" width = "500">

**Comment by tessig** [comment]
Hi, thanks for reaching out.
The dist folder is supposed to be created by the command `make frontend-build`.
The end of the command's output should look like this:
```
🥕 Initialize config
🥕 Dispatch command: config
🥕 Dispatch command: build
🥕 Job start: Pug Compile
🥕 Job start: Copy static assets
🥕 Job start: Webpack (Complete)
🥕 Job finished: Copy static assets in 947ms
🥕 Job finished: Pug Compile in 1721ms
🥕 Job finished: Webpack (Complete) in 13529ms
🥕 Flamingo Carotene finished - successfully
```

Can you please double check that `make frontend-build` has run and provide us the error messages if it doesn't run successfully?

**Comment by Yosutta** [comment]
Oh wow thank you.
It works like a charm now.
I thought i run the line ```make frontend-build``` before but it does not work at that time.
