### ISSUE TITLE
flamingo-om3

### ISSUE THREAD

**Issue by suifengtec** [i-love-flamingo/commerce-demo-carotene#4]
Hi!
when I tried to run `make serve` , but it failed, may caused by this private package.

```bash

go: go.aoe.com/flamingo-om3/v3@v3.0.0-alpha9: reading go.aoe.com/flamingo-om3/go.mod at revision v3.0.0-alpha9: unknown revision v3.0.0-alpha9

```
I tried to get this module, but I failed, may caused by this package is private, I do not have the permisson?

Common user can not access this repo, it's only for AOE staff?

```bash

git@gitlab.aoe.com/shared/flamingo/flamingo-om3.git

```

and, there maybe have a type error

```bash

cannot use r.queryResolver (variable of type *queryResolver) as QueryResolver value in return statement: wrong type for method CommerceCategory

```

**Comment by danielpoe** [comment]
Ups thank you.
That dependency made it in by mistake and is of course not required.

I removed it - can you please retry
